#!/usr/bin/env sh

# IBM Load Leveler job control file

# @ job_name = lab3
# @ job_type = MPICH
# @ class = small
# @ node = 4
# @ initialdir = /gpfs/home/iu7/stud051/labs
# @ output = $(initialdir)/$(job_name).$(jobid).stdout
# @ error = $(initialdir)/$(job_name).$(jobid).stderr
# @ queue

mpdboot -r ssh -n $LOADL_TOTAL_TASKS -f $LOADL_HOSTFILE

mpirun -r ssh -machinefile $LOADL_HOSTFILE -n $LOADL_TOTAL_TASKS ./$LOADL_JOB_NAME

mpdallexit
